// This file is automatically generated by include/decompose/detail/generate_decompose_with_structured_binding.py.
// DateTime: 2022-06-18 12:35:30.999045

#pragma once

#include "util.hpp"

namespace decompose::detail{
template<class T>
constexpr int structured_binding_num = []{
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wempty-decomposition"
    constexpr auto c0 = [](auto&& t) -> decltype(({
                auto&& [] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 0>();
            })) {
        return {};
    };
    constexpr auto c1 = [](auto&& t) -> decltype(({
                auto&& [_0] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 1>();
            })) {
        return {};
    };
    constexpr auto c2 = [](auto&& t) -> decltype(({
                auto&& [_0, _1] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 2>();
            })) {
        return {};
    };
    constexpr auto c3 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 3>();
            })) {
        return {};
    };
    constexpr auto c4 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 4>();
            })) {
        return {};
    };
    constexpr auto c5 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 5>();
            })) {
        return {};
    };
    constexpr auto c6 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 6>();
            })) {
        return {};
    };
    constexpr auto c7 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 7>();
            })) {
        return {};
    };
    constexpr auto c8 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 8>();
            })) {
        return {};
    };
    constexpr auto c9 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 9>();
            })) {
        return {};
    };
    constexpr auto c10 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 10>();
            })) {
        return {};
    };
    constexpr auto c11 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 11>();
            })) {
        return {};
    };
    constexpr auto c12 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 12>();
            })) {
        return {};
    };
    constexpr auto c13 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 13>();
            })) {
        return {};
    };
    constexpr auto c14 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 14>();
            })) {
        return {};
    };
    constexpr auto c15 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 15>();
            })) {
        return {};
    };
    constexpr auto c16 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 16>();
            })) {
        return {};
    };
    constexpr auto c17 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 17>();
            })) {
        return {};
    };
    constexpr auto c18 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 18>();
            })) {
        return {};
    };
    constexpr auto c19 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 19>();
            })) {
        return {};
    };
    constexpr auto c20 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 20>();
            })) {
        return {};
    };
    constexpr auto c21 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 21>();
            })) {
        return {};
    };
    constexpr auto c22 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 22>();
            })) {
        return {};
    };
    constexpr auto c23 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 23>();
            })) {
        return {};
    };
    constexpr auto c24 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 24>();
            })) {
        return {};
    };
    constexpr auto c25 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 25>();
            })) {
        return {};
    };
    constexpr auto c26 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 26>();
            })) {
        return {};
    };
    constexpr auto c27 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 27>();
            })) {
        return {};
    };
    constexpr auto c28 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 28>();
            })) {
        return {};
    };
    constexpr auto c29 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 29>();
            })) {
        return {};
    };
    constexpr auto c30 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 30>();
            })) {
        return {};
    };
    constexpr auto c31 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 31>();
            })) {
        return {};
    };
    constexpr auto c32 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 32>();
            })) {
        return {};
    };
    constexpr auto c33 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 33>();
            })) {
        return {};
    };
    constexpr auto c34 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 34>();
            })) {
        return {};
    };
    constexpr auto c35 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 35>();
            })) {
        return {};
    };
    constexpr auto c36 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 36>();
            })) {
        return {};
    };
    constexpr auto c37 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 37>();
            })) {
        return {};
    };
    constexpr auto c38 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 38>();
            })) {
        return {};
    };
    constexpr auto c39 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 39>();
            })) {
        return {};
    };
    constexpr auto c40 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 40>();
            })) {
        return {};
    };
    constexpr auto c41 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 41>();
            })) {
        return {};
    };
    constexpr auto c42 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 42>();
            })) {
        return {};
    };
    constexpr auto c43 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 43>();
            })) {
        return {};
    };
    constexpr auto c44 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 44>();
            })) {
        return {};
    };
    constexpr auto c45 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 45>();
            })) {
        return {};
    };
    constexpr auto c46 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 46>();
            })) {
        return {};
    };
    constexpr auto c47 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 47>();
            })) {
        return {};
    };
    constexpr auto c48 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 48>();
            })) {
        return {};
    };
    constexpr auto c49 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 49>();
            })) {
        return {};
    };
    constexpr auto c50 = [](auto&& t) -> decltype(({
                auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49] = std::forward<decltype(t)>(t);
                std::integral_constant<int, 50>();
            })) {
        return {};
    };


    constexpr auto c_error = [](detail::any&&) -> std::integral_constant<int, -1> {
        return {};
    };
    constexpr auto cnt_func = detail::overload_t{c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c_error};
    
    using cnt_t = decltype(cnt_func(std::declval<T>()));
    return cnt_t::value;
    #pragma clang diagnostic pop
}();

template<class T>
concept decomposable_with_structured_binding = (structured_binding_num<T> >= 0);

/** @brief Decompose a struct/array/tuple with structured binding and call `f` with the decomposed elements.
  * @param t The struct/array/tuple to decompose.
  * @param f The function to call with the decomposed elements.
  * @return The return value of `f`.
*/
template<class T, class F>
constexpr decltype(auto) decompose_with_structured_binding(T&& t, F&& f){

    constexpr int sb_num = structured_binding_num<T>;
    if constexpr(sb_num == -1){
        static_assert([]<class = void>{return false;}(), 
            "T could not be decomposed by structured binding. "
            "Possible causes: "
            "1. T has a private/protected field. "
            "2. T's fields come from different base classes. "
            "3. T has a field of an anonymous union type. "
            "4. T has more than `max_n`(= 50) fields. "
            "In the last case, you can increase the size of `max_n` in " 
            "include/decompose/detail/generate_decompose_with_structured_binding.py and regenerate the code.\n");
    } else{

        #pragma clang diagnostic push
        #pragma clang diagnostic ignored "-Wempty-decomposition"
        constexpr auto f0 = [](std::integral_constant<int, 0>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)();
        };
        constexpr auto f1 = [](std::integral_constant<int, 1>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0));
        };
        constexpr auto f2 = [](std::integral_constant<int, 2>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1));
        };
        constexpr auto f3 = [](std::integral_constant<int, 3>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2));
        };
        constexpr auto f4 = [](std::integral_constant<int, 4>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3));
        };
        constexpr auto f5 = [](std::integral_constant<int, 5>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4));
        };
        constexpr auto f6 = [](std::integral_constant<int, 6>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5));
        };
        constexpr auto f7 = [](std::integral_constant<int, 7>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6));
        };
        constexpr auto f8 = [](std::integral_constant<int, 8>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7));
        };
        constexpr auto f9 = [](std::integral_constant<int, 9>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8));
        };
        constexpr auto f10 = [](std::integral_constant<int, 10>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9));
        };
        constexpr auto f11 = [](std::integral_constant<int, 11>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10));
        };
        constexpr auto f12 = [](std::integral_constant<int, 12>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11));
        };
        constexpr auto f13 = [](std::integral_constant<int, 13>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12));
        };
        constexpr auto f14 = [](std::integral_constant<int, 14>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13));
        };
        constexpr auto f15 = [](std::integral_constant<int, 15>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14));
        };
        constexpr auto f16 = [](std::integral_constant<int, 16>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15));
        };
        constexpr auto f17 = [](std::integral_constant<int, 17>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16));
        };
        constexpr auto f18 = [](std::integral_constant<int, 18>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17));
        };
        constexpr auto f19 = [](std::integral_constant<int, 19>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18));
        };
        constexpr auto f20 = [](std::integral_constant<int, 20>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19));
        };
        constexpr auto f21 = [](std::integral_constant<int, 21>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20));
        };
        constexpr auto f22 = [](std::integral_constant<int, 22>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21));
        };
        constexpr auto f23 = [](std::integral_constant<int, 23>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22));
        };
        constexpr auto f24 = [](std::integral_constant<int, 24>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23));
        };
        constexpr auto f25 = [](std::integral_constant<int, 25>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24));
        };
        constexpr auto f26 = [](std::integral_constant<int, 26>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25));
        };
        constexpr auto f27 = [](std::integral_constant<int, 27>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26));
        };
        constexpr auto f28 = [](std::integral_constant<int, 28>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27));
        };
        constexpr auto f29 = [](std::integral_constant<int, 29>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28));
        };
        constexpr auto f30 = [](std::integral_constant<int, 30>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29));
        };
        constexpr auto f31 = [](std::integral_constant<int, 31>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30));
        };
        constexpr auto f32 = [](std::integral_constant<int, 32>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31));
        };
        constexpr auto f33 = [](std::integral_constant<int, 33>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32));
        };
        constexpr auto f34 = [](std::integral_constant<int, 34>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33));
        };
        constexpr auto f35 = [](std::integral_constant<int, 35>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34));
        };
        constexpr auto f36 = [](std::integral_constant<int, 36>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35));
        };
        constexpr auto f37 = [](std::integral_constant<int, 37>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36));
        };
        constexpr auto f38 = [](std::integral_constant<int, 38>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37));
        };
        constexpr auto f39 = [](std::integral_constant<int, 39>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38));
        };
        constexpr auto f40 = [](std::integral_constant<int, 40>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39));
        };
        constexpr auto f41 = [](std::integral_constant<int, 41>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40));
        };
        constexpr auto f42 = [](std::integral_constant<int, 42>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41));
        };
        constexpr auto f43 = [](std::integral_constant<int, 43>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42));
        };
        constexpr auto f44 = [](std::integral_constant<int, 44>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43));
        };
        constexpr auto f45 = [](std::integral_constant<int, 45>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43), std::forward<decltype(_44)>(_44));
        };
        constexpr auto f46 = [](std::integral_constant<int, 46>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43), std::forward<decltype(_44)>(_44), std::forward<decltype(_45)>(_45));
        };
        constexpr auto f47 = [](std::integral_constant<int, 47>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43), std::forward<decltype(_44)>(_44), std::forward<decltype(_45)>(_45), std::forward<decltype(_46)>(_46));
        };
        constexpr auto f48 = [](std::integral_constant<int, 48>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43), std::forward<decltype(_44)>(_44), std::forward<decltype(_45)>(_45), std::forward<decltype(_46)>(_46), std::forward<decltype(_47)>(_47));
        };
        constexpr auto f49 = [](std::integral_constant<int, 49>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43), std::forward<decltype(_44)>(_44), std::forward<decltype(_45)>(_45), std::forward<decltype(_46)>(_46), std::forward<decltype(_47)>(_47), std::forward<decltype(_48)>(_48));
        };
        constexpr auto f50 = [](std::integral_constant<int, 50>, auto&& t, auto&& f) -> decltype(auto) {
            auto&& [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49] = std::forward<decltype(t)>(t);
            return std::forward<decltype(f)>(f)(std::forward<decltype(_0)>(_0), std::forward<decltype(_1)>(_1), std::forward<decltype(_2)>(_2), std::forward<decltype(_3)>(_3), std::forward<decltype(_4)>(_4), std::forward<decltype(_5)>(_5), std::forward<decltype(_6)>(_6), std::forward<decltype(_7)>(_7), std::forward<decltype(_8)>(_8), std::forward<decltype(_9)>(_9), std::forward<decltype(_10)>(_10), std::forward<decltype(_11)>(_11), std::forward<decltype(_12)>(_12), std::forward<decltype(_13)>(_13), std::forward<decltype(_14)>(_14), std::forward<decltype(_15)>(_15), std::forward<decltype(_16)>(_16), std::forward<decltype(_17)>(_17), std::forward<decltype(_18)>(_18), std::forward<decltype(_19)>(_19), std::forward<decltype(_20)>(_20), std::forward<decltype(_21)>(_21), std::forward<decltype(_22)>(_22), std::forward<decltype(_23)>(_23), std::forward<decltype(_24)>(_24), std::forward<decltype(_25)>(_25), std::forward<decltype(_26)>(_26), std::forward<decltype(_27)>(_27), std::forward<decltype(_28)>(_28), std::forward<decltype(_29)>(_29), std::forward<decltype(_30)>(_30), std::forward<decltype(_31)>(_31), std::forward<decltype(_32)>(_32), std::forward<decltype(_33)>(_33), std::forward<decltype(_34)>(_34), std::forward<decltype(_35)>(_35), std::forward<decltype(_36)>(_36), std::forward<decltype(_37)>(_37), std::forward<decltype(_38)>(_38), std::forward<decltype(_39)>(_39), std::forward<decltype(_40)>(_40), std::forward<decltype(_41)>(_41), std::forward<decltype(_42)>(_42), std::forward<decltype(_43)>(_43), std::forward<decltype(_44)>(_44), std::forward<decltype(_45)>(_45), std::forward<decltype(_46)>(_46), std::forward<decltype(_47)>(_47), std::forward<decltype(_48)>(_48), std::forward<decltype(_49)>(_49));
        };

        return detail::overload_t{f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26, f27, f28, f29, f30, f31, f32, f33, f34, f35, f36, f37, f38, f39, f40, f41, f42, f43, f44, f45, f46, f47, f48, f49, f50}(std::integral_constant<int, sb_num>{}, std::forward<T>(t), std::forward<F>(f));

    }
        #pragma clang diagnostic pop
}


} // namespace decompose::detail
